# Generated by Django 4.0.6 on 2023-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('des_title', models.CharField(max_length=230)),
                ('des_title_des', models.TextField()),
                ('des_detail', models.TextField()),
                ('extra_des', models.TextField()),
                ('thumbnailabout', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('email', models.CharField(max_length=230)),
                ('phone', models.CharField(max_length=230)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=230)),
                ('birthday', models.CharField(max_length=230)),
                ('website', models.CharField(max_length=230)),
                ('city', models.CharField(max_length=230)),
                ('loc_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True)),
                ('loc_src_map', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_owner', models.CharField(max_length=200)),
                ('title_fixed', models.CharField(max_length=200)),
                ('title_job', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnailbio', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('project_des', models.TextField()),
                ('project_owner', models.CharField(max_length=230)),
                ('project_owner_title', models.CharField(max_length=230)),
                ('ownerimg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.TextField()),
                ('social_link', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
