# Generated by Django 4.0.6 on 2023-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_src',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
